urls.py
from django.conf.urls import url
from django.contrib import admin

from .views.drs import viz_drs, data_drs
from .views.stix import stix_view
from .views.timeline import viz_timeline, data_timeline
from .views.report import report_list, report_view, stix_report
from .views.actor import actor_list, actor_view, actor_viz
from .views.malware import malware_list, malware_view
from .views.identity import identity_list, identity_view
from .views.indicator import indicator_list, indicator_view
from .tables import ReportData, ThreatActorData, IdentityData, MalwareData, IndicatorData

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^report/$', report_list),
    url(r'^actor/$', actor_list),
    url(r'^threat-actor/$', actor_list),
    url(r'^malware/$', malware_list),
    url(r'^identity/$', identity_list),
    url(r'^indicator/$', indicator_list),
    url(r'^data/report/', ReportData.as_view(), name="report_data"),
    url(r'^data/threat-actor/', ThreatActorData.as_view(), name="threatactor_data"),
    url(r'^data/malware/', MalwareData.as_view(), name="malware_data"),
    url(r'^data/identity/', IdentityData.as_view(), name="identity_data"),
    url(r'^data/indicator/', IndicatorData.as_view(), name="inicator_data"),
    url(r'^report/(?P<id>\d+)$', report_view),
    url(r'^report/(?P<id>\d+).json$', stix_report),
    url(r'^malware/(?P<id>\d+)$', malware_view),
    url(r'^actor/(?P<id>\d+)$', actor_view),
    url(r'^threat-actor/(?P<id>\d+)$', actor_view),
    url(r'^identity/(?P<id>\d+)$', identity_view),
    url(r'^viz/actor/(?P<id>\d+)*$', actor_viz),
    url(r'^viz/drs/$', viz_drs),
    url(r'^data/drs/$', data_drs),
    url(r'^timeline/$', viz_timeline),
    url(r'^data/timeline/$', data_timeline),
    url(r'^$', stix_view),
]

forms.py
from django import forms
from django.db.models import Q

from .models import *
import STreifen.models as mymodels

from operator import itemgetter

import logging
logging.basicConfig(level=logging.DEBUG)

class InputForm(forms.Form):
    input = forms.CharField(
        widget=forms.Textarea(
            attrs={'style':'height:400px;'}
        )
    )

class TimelineForm(forms.Form):
    models = [
        "report",
        "sighting",
        #"campaign",
        #"attack-pattern",
    ]
    objects = forms.ModelMultipleChoiceField(
        queryset=STIXObjectType.objects.filter(
            name__in=models
        ),
        widget=forms.CheckboxSelectMultiple(attrs={"checked":""})
    )
    def __init__(self, *args, **kwargs):
        super(TimelineForm, self).__init__(*args, **kwargs)
        self.fields["objects"].required = False

class RelationshipForm(forms.ModelForm):
    class Meta:
        model = Relationship
        fields = [
            "source_ref",
            "relationship_type",
            "target_ref",
            "description",
        ]

class SightingForm(forms.ModelForm):
    class Meta:
        model = Sighting
        fields = [
            "where_sighted_refs",
            "sighting_of_ref",
            "first_seen",
            "last_seen",
            "description",
        ]
    def __init__(self, *args, **kwargs):
        super(SightingForm, self).__init__(*args, **kwargs)
        self.fields["where_sighted_refs"].choices = object_choices(
            ids=STIXObjectID.objects.filter(
                object_id__startswith="identity--",
            ),
            dummy=True
        )

class ThreatActorForm(forms.ModelForm):
    class Meta:
        model = ThreatActor
        fields = [
            "name",
            "labels",
            "aliases",
            "description",
        ]
        #widgets = {
        #    "labels":forms.CheckboxSelectMultiple(),
        #}

class MalwareForm(forms.ModelForm):
    class Meta:
        model = Malware
        fields = [
            "name",
            "description",
            "labels",
        ]

class AttackPatternForm(forms.ModelForm):
    class Meta:
        model = AttackPattern
        fields = [
            "name",
            "description",
        ]

class IdentityForm(forms.ModelForm):
    class Meta:
        model = Identity
        fields = [
            "name",
            "identity_class",
            #"sectors",
            "labels",
            "description",
        ]
    def __init__(self, *args, **kwargs):
        super(IdentityForm, self).__init__(*args, **kwargs)
        self.fields["identity_class"].initial = "organization"


class DefinedRelationshipForm(forms.Form):
    relation = forms.ModelChoiceField(
        queryset=DefinedRelationship.objects.all()
    )

class SelectObjectForm(forms.Form):
    type = forms.ModelChoiceField(
        queryset=STIXObjectType.objects.filter(
            name__in=[
                "identity",
                "attack-pattern",
                "malware",
                "threat-actor",
                "relationship",
                "sighting",
            ]
        ),
    )
    def __init__(self, *args, **kwargs):
        super(SelectObjectForm, self).__init__(*args, **kwargs)
        self.fields["type"].required = False


def get_related_obj(obj):
    rels = Relationship.objects.filter(
        Q(source_ref__object_id__startswith=obj.object_id)\
        |Q(target_ref__object_id__startswith=obj.object_id)\
    )
    print(rels)
    sights = Sighting.objects.filter(
        Q(where_sighted_refs__object_id__startswith=obj.object_id)\
        |Q(sighting_of_ref__object_id__startswith=obj.object_id)\
    )
    objects = [obj]
    objdict = {}
    for rel in rels.all():
        o = None
        if rel.source_ref == obj.object_id:
            if not rel.target_ref.object_id in objdict:
                o = get_obj_from_id(rel.target_ref)
                objdict[rel.target_ref.object_id] = o
        elif rel.target_ref == obj.object_id:
            if not rel.source_ref.object_id in objdict:
                o = get_obj_from_id(rel.source_ref)
                objdict[rel.source_ref.object_id] = o
        if o:
            if not o in objects:
                objects.append(o)
    return rels, objects

def get_obj_from_id(soi):
    sot = soi.object_id.split('--')[0]
    m = ""
    for s in sot.split('-'):
        m += s.capitalize()
    obj = getattr(mymodels, m).objects.filter(object_id=soi)
    if obj.count() == 1:
        return obj.all()[0]
    else:
        logging.error("Object not found: "+soi.object_id)
    return None

def object_choices(ids=STIXObjectID.objects.all(), dummy=False):
    choices = []
    if dummy:
        choices = [("","----------")]
    for soi in ids:
        obj = get_obj_from_id(soi)
        name = ""
        if not obj:
            logging.error("Could not get object: "+soi.object_id)
            if soi.id:
                soi.delete()
        else:
            if obj.object_type.name == 'relationship':
                src = get_obj_from_id(obj.source_ref)
                tgt = get_obj_from_id(obj.target_ref)
                rel = obj.relationship_type.name
                if src and tgt and rel:
                    name = " ".join([src.name, rel, tgt.name])
            elif obj.object_type.name == 'sighting':
                sor = get_obj_from_id(obj.sighting_of_ref)
                tgt = []
                for wsr in obj.where_sighted_refs.all():
                    i = get_obj_from_id(wsr)
                    if i:
                        tgt.append(i.name)
                if sor and tgt:
                    name = ",".join(tgt) + " sighted " + sor.name
            else:
                if hasattr(obj, 'name'):
                    name = obj.name
            if name:
                choices.append((
                #choices += ((
                    obj.object_id.id,
                    obj.object_type.name + " : " + name,
                ))
    if choices:
        choices.sort(key=itemgetter(1))
    return choices

class AddObjectForm(forms.Form):
    objects = forms.ModelMultipleChoiceField(
        queryset=STIXObjectID.objects.all()
    )
    def __init__(self, *args, **kwargs):
        super(AddObjectForm, self).__init__(*args, **kwargs)
        self.fields["objects"].choices = object_choices()

class ReportLabelForm(forms.Form):
    label = forms.ModelMultipleChoiceField(
        queryset=ReportLabel.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={"checked":""})
    )

class ReportRefForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = [
            "object_refs",
        ]
        widgets = {
            "object_refs":forms.CheckboxSelectMultiple(),
        }

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = [
            "name",
            "created_by_ref",
            "published",
            "labels",
            "description",
            #"object_refs",
        ]
        widgets = {
            #"labels":forms.CheckboxSelectMultiple(),
            #"object_refs":forms.CheckboxSelectMultiple(),
        }
    def __init__(self, *args, **kwargs):
        super(ReportForm, self).__init__(*args, **kwargs)
        self.fields["created_by_ref"].choices = object_choices(
            ids=STIXObjectID.objects.filter(
                object_id__startswith="identity--",
            ),
            dummy=True
        )

class TypeSelectForm(forms.Form):
    types = forms.ModelMultipleChoiceField(
        queryset=STIXObjectType.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={"checked":""})
    )
    relation = forms.ModelMultipleChoiceField(
        queryset=RelationshipType.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={"checked":""})
    )
    def __init__(self, *args, **kwargs):
        super(TypeSelectForm, self).__init__(*args, **kwargs)
        self.fields["types"].required = False
        self.fields["relation"].required = False

class IndicatorForm(forms.ModelForm):
    class Meta:
        model = Indicator
        fields = [
            "name",
            "labels",
            "description",
            #"valid_from",
            #"valid_until",
            #"pattern",
        ]

class PatternForm(forms.ModelForm):
    class Meta:
        model = IndicatorPattern
        fields = [
            "property",
            "value",
        ]

views/actor.py
from django.shortcuts import render, redirect
from django.db.models import Q
import STreifen.models as mymodels
import STreifen.forms as myforms
from ..models import *
from ..forms import *
from collections import OrderedDict

def actor_viz(request, id=None):
    rels = Relationship.objects.filter(
        Q(source_ref__object_id__startswith='threat-actor')\
        |Q(target_ref__object_id__startswith='threat-actor')\
    )
    data = target_stats(rels, id)
    c = {
        "data": data,
    }
    return render(request, 'actor_viz.html', c)

def target_stats(rels, id=None):
    ati = rels.filter(
        source_ref__object_id__startswith='threat-actor',
        relationship_type__name='targets',
        target_ref__object_id__startswith='identity',
    )
    if id:
        actor = ThreatActor.objects.get(id=id)
        ati = ati.filter(source_ref__object_id=actor.object_id)
    data = {}
    for a in ati.all():
        act = get_obj_from_id(a.source_ref)
        if not act.name in data:
            data[act.name] = {
                "inner":{},
                "value":0,
            }
        tgt = get_obj_from_id(a.target_ref)
        if tgt:
            data[act.name]["value"] += 1
            label = tgt.labels.all()
            if label:
                if not label[0].value in data[act.name]["inner"]:
                    data[act.name]["inner"][label[0].value] = 1
                else:
                    data[act.name]["inner"][label[0].value] += 1
    for d in data.items():
        d[1]["inner"] = OrderedDict(
            sorted(
                d[1]["inner"].items(),
                key=lambda kv:kv[1],
                reverse=True
            )
        )
    data = OrderedDict(
        sorted(
            data.items(),
            key=lambda kv: kv[1]["value"],
            reverse=True
        )
    )
    return data

def actor_list(request):
    rels = Relationship.objects.filter(
        Q(source_ref__object_id__startswith='threat-actor')\
        |Q(target_ref__object_id__startswith='threat-actor')\
    )
    data = target_stats(rels)
    form = ThreatActorForm()
    if request.method == "POST":
        if 'create' in request.POST:
            form = ThreatActorForm(request.POST)
            if form.is_valid():
                a = form.save()
                taa, created = ThreatActorAlias.objects.get_or_create(
                    name = a.name
                )
                a.aliases.add(taa)
                a.save()
                return redirect("/actor/")
    c = {
        "form": form,
        "rels": rels,
        "data": data,
    }
    return render(request, 'actor_list.html', c)

def _object_form(name, request=None, actor=None):
    post = None
    if request:
        if request.method == 'POST':
            post = request.POST
    if name == "identity":
        return IdentityForm(post)
    elif name == "attack-pattern":
        return AttackPatternForm(post)
    elif name == "malware":
        return MalwareForm(post)
    elif name == "threat-actor":
        return ThreatActorForm(post)
    return False

def actor_view(request, id):
    actor = ThreatActor.objects.get(id=id)
    form = ThreatActorForm(instance=actor)

    rels, objects = get_related_obj(actor)
    #selected = None
    #oform = None
    atform = AddObjectForm()
    if request.method == "POST":
        #print(request.POST)
        if 'update' in request.POST:
            form = ThreatActorForm(request.POST, instance=actor)
            if form.is_valid():
                form.save()
                redirect("/actor/"+id)
        elif 'delete' in request.POST:
            #actor.delete()
            return redirect("/actor/")
        elif 'relation' in request.POST:
            rid = request.POST.get('relation')
            r = DefinedRelationship.objects.get(id=rid)
            source_ref = None
            target_ref = None
            rel_type = r.type
            if r.source == actor.object_type:
                oform = _object_form(r.target.name, request=request)
                source_ref = actor.object_id
            elif r.target == actor.object_type:
                oform = _object_form(r.source.name, request=request)
                target_ref = actor.object_id
            drform.fields["relation"].initial = rid
            if 'create_obj' in request.POST:
                if oform.is_valid():
                    created = oform.save
                    if not source_ref:
                        source_ref = created.object_id
                    elif not target_ref:
                        target_ref = created.object_id
                    Relationship.objects.create(
                        source_ref = source_ref,
                        target_ref = target_ref,
                        relationship_type = rel_type,
                    )
                    redirect("/actor/"+id)
        elif 'add_tgt' in request.POST:
            atform = AddObjectForm(request.POST)
            if atform.is_valid():
                tgts = atform.cleaned_data["objects"]
                rtype = RelationshipType.objects.get(name='targets')
                for tgt in tgts:
                    Relationship.objects.get_or_create(
                        source_ref = actor.object_id,
                        relationship_type = rtype,
                        target_ref = tgt,
                    )
                redirect("/actor/"+id)
    atform.fields["objects"].choices = object_choices(
        ids=STIXObjectID.objects.filter(
            object_id__startswith='identity'
        )
    )
    c = {
        "form": form,
        #"selected": selected,
        #"oform": oform,
        "atform": atform,
        "actor": actor,
        #"obj": actor,
        "rels": rels,
        "objects":objects,
    }
    return render(request, 'actor_view.html', c)
    #return render(request, 'base_view.html', c)

templates/actor_view.html
{% extends "base.html" %}

{% block title %}
<title>Threat Actor: {{actor.name}}</title>
{% endblock %}

{% block jquery %}
<script type="text/javascript" src="/static/d3/d3.js"></script>
<link rel="stylesheet" type="text/css" href="/static/psd3/psd3.css">
<script type="text/javascript" src="/static/psd3/psd3.js"></script>
<script>
$(document).ready(
    function(){
        $("select#id_relation").change(function(){
            $.ajax({
                type: 'POST',
                data: {
                    relation:$('#id_relation').val(),
                    csrfmiddlewaretoken:'{{csrf_token}}',
                },
                success: function(result){
                    form = $(result).find("#create_form");
                    $("#create_form").html(form);
                }
            });
        });
    }
);
</script>
{% endblock%}

{% block container %}

<div class="modal" id="actor_form" role="dialog">
<div class="modal-dialog"><div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h4 class="modal-title">Edit Threat Actor</h4>
</div>
<div class="modal-body">
<form method="post">{% csrf_token %}
<div class="col-md-12">
<div class="col-md-7">
Name:
{{form.name}}
Alias:
{{form.aliases}}
Description:
{{form.description}}
</div>
<div class="col-md-5">
Labels:
{{form.labels}}
</div>
</div>
<input class="btn btn-primary btn-sm" type="submit" name="update" value="Update">
<input class="btn btn-danger btn-sm" type="submit" name="delete" value="Delete">
</form>
</div><!--/.modal-body-->
</div><!--/.modal-content-->
</div><!--/.modal-dialog-->
</div><!--/.modal-->

<div class="modal" id="add_tgt" role="dialog">
<div class="modal-dialog"><div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h4 class="modal-title">Add Target</h4>
</div>
<div class="modal-body">
<form id="add_tgt_form" method="post">{% csrf_token %}
{{atform}}
<input class="btn btn-primary btn-sm" type="submit" name="add_tgt" value="Add">
</form>
</div><!--/.modal-body-->
</div><!--/.modal-content-->
</div><!--/.modal-dialog-->
</div><!--/.modal-->

<div class="modal" id="object_form" role="dialog">
<div class="modal-dialog"><div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h4 class="modal-title">Create Object</h4>
</div>
<div class="modal-body">
<form id="select_form" method="post">{% csrf_token %}
<div >{{drform}}</div>
<div id="create_form" >
{% if oform %}
<hr>
<table>
{{oform.as_table}}
</table>
<input class="btn btn-primary btn-sm" type="submit" name="create_obj" value="Create">
{% endif %}
</div><!--/#create_form-->
</form>
</div><!--/.modal-body-->
</div><!--/.modal-content-->
</div><!--/.modal-dialog-->
</div><!--/.modal-->


<div class="col-md-12" id="actor" >

<div class="panel panel-primary">

<div class="panel-heading">
<div  >
<h4>
<a class="btn btn-default btn-xs" href="">{{actor.id}}</a>
<a class="btn btn-warning btn-xs" data-toggle="modal" href="#actor_form">Edit</a>
<a data-toggle="collapse" href="#actor_body" style="color:white">
{{actor.name}}
({{actor.object_id}})
</a>
</h4>
</div>
</div><!--.panel-heading-->

<div id="actor_body" class="panel-collapse collapse in">

<div class="panel-body">

<div class="col-md-12">

<div class="col-md-3">
<table class="table table-condensed">
<tr><th class="col-md-3">Aliases</th>
<td>
{% for a in actor.aliases.all %}
{{a.name}}<br>
{% endfor %}
</td></tr>
<tr><th class="col-md-3">Labels</th>
<td>
{% for l in actor.labels.all %}
{{l.value}}<br>
{% endfor %}
</td></tr>
</table>
</div>

<div class="col-md-3">
<table class="table table-condensed">
<tr>
<th class="col-md-4">Created</th><td>{{actor.created}}</td></tr>
<th >Modified</th><td>{{actor.modified}}</td></tr>
</table>
</div>

<div class="col-md-6">
<table class="table table-condensed">
<tr>
<th class="col-md-3">Description</th>
<td><pre>{{actor.description}}</pre></td>
</tr>
</table>
</div>

</div>

</div><!--/.panel-body-->

</div><!--/.collapse-->

</div><!--/.panel-->

</div><!--/report-->

{% if stix %}
<div class="col-md-12">
<div class="panel panel-primary">
<div class="panel-heading">
<a data-toggle="collapse" href="#collapse2" style="color:white;">
STIX
</a></div><!--/.panel-heading-->
<div id="collapse2"class="panel-collapse collapse">
<div class="panel-body">
<textarea id="stix" read-only style="height:500px;">{{stix}}</textarea>
</div><!--/.panel-body-->
</div><!--/.panel-collapse-->
</div><!--/.panel-->
</div>
{% endif %}

<div id="tables" class="col-md-12">
<ul class="nav nav-pills">
  <li class="active"><a data-toggle="tab" href="#relation">Relationship</a></li>
  <li ><a data-toggle="tab" href="#objects">Objects</a></li>
</ul>

<div class="panel panel-primary">
<div class="panel-heading"></div>
<div class="panel-body">

<div class="tab-content">

<div class="tab-pane" id="objects" >
<table id="objects_table" class="table table-condensed table-stripe table-hover display" width="100%">
<!--
<a class="btn btn-primary btn-md" data-toggle="modal" href="#object_form">Create</a>
-->
<thead><tr>
<th class="col-md-1">ID</th>
<th class="col-md-2">Type</th>
<th class="col-md-2">Name</th>
<th class="col-md-2">Label</th>
<th class="col-md-5">Object ID</th>
</tr></thead>
<tbody>
{% for o in objects %}
<tr>
<td><a class="btn btn-primary btn-xs"href="/{{o.object_type.name}}/{{o.id}}">{{o.id}}</td>
<td>{{o.object_type.name}}</td>
<td>{{o.name}}</td>
<td>
{% if o.labels %}
{% for l in o.labels.all %}
{{l.value}}<br>
{% endfor %}
{% endif %}
</td>
<td>{{o.object_id.object_id}}</td>
</tr>
{% endfor %}
</tbody>
</table>
</div><!--/#identity-->

<div class="tab-pane active" id="relation" >
Add
<a class="btn btn-primary btn-sm" data-toggle="modal" href="#add_tgt">Target</a>
<table id="relation_table" class="table table-condensed table-stripe table-hover display" width="100%">
<thead>
<th class="col-md-1">ID</th>
<th class="col-md-2">Source</th>
<th class="col-md-2">Type</th>
<th class="col-md-2">Target</th>
<th class="col-md-5">Ref</th>
</thead>
<tbody>
{% for rel in rels %}
<tr>
<td>{{rel.id}}</td>
<td>
{% for obj in objects %}
{% ifequal obj.object_id rel.source_ref %}
{{obj.name}}
{% endifequal %}
{% endfor %}
</td>
<td>{{rel.relationship_type}}</td>
<td>
{% for obj in objects %}
{% ifequal obj.object_id rel.target_ref %}
{{obj.name}}
{% endifequal %}
{% endfor %}
</td>
<td>{{rel.object_id}}</td>
</tr>
{% endfor %}
</tbody>
</table>
</div><!--/#identity-->

</div><!--/tab-content-->

</div><!--/.panel-body-->
</div><!--/.panel-->

</div><!--/tables-->

{% endblock %}

templates/drs_vis.html
{% extends "base.html" %}

{% block title %}
<title>STIX Defined Relationships</title>
{% endblock %}

{% block jquery %}
<script>
function drawvis(){
    var data = $("form").serialize();
    $.ajax({
            type: 'POST',
            url: '/data/drs/',
            data: data,
            success: function(result){
                var network = visNetwork(
                    result["nodes"],
                    result["edges"]
                );
                network.redraw();
            }
    });
};
$(document).ready(
    function(){
        drawvis();
        $("input#select_types").click(function(){
            if($(this).prop("checked")){
                $('ul#id_types :checkbox').prop('checked',true);
            }else{
                $('ul#id_types :checkbox').prop('checked',false);
            };
        });
        $("input#select_relation").click(function(){
            if($(this).prop("checked")){
                $('ul#id_relation :checkbox').prop('checked',true);
            }else{
                $('ul#id_relation :checkbox').prop('checked',false);
            };
        });
        $("input").change(function(){
            drawvis();
        });
    }
);
</script>
{% endblock %}

{% block container %}

<div class="col-md-12">
<div class="panel panel-primary">
<div class="panel-heading">STIX Defined Relationships</div>
<div class="panel-body">

<div class="col-md-7" style="margin: 0 auto;height:500px" id="network" ></div>

<div class="col-md-5" >
<form method=post>{% csrf_token %}
<div class="col-md-7" id="types_form">
<input type="checkbox" id="select_types" checked>types</input>
{{tsform.types}}
</div>
<div class="col-md-5" id="rel_form">
<input type="checkbox" id="select_relation" checked>relationship</input>
{{tsform.relation}}
</div>
</form>
</div>

</div><!--/panel-body-->
</div><!--/panel-->
</div>

<!--
<script type="text/javascript">
var nodes = [
{% for n in nodes %}{
	'id':'{{n.id}}',
	'label':'{{n.label}}',
	'group':'{{n.group}}',
	'title': '<table>{% for t in n.title %}<tr><td>{{t|escapejs}}</td></tr>{% endfor %}</table>',
},
{% endfor %}];

var edges = [
{% for e in edges %}{
	'from':'{{e.from}}',
	'to':'{{e.to}}',
	'label':'{{e.label}}',
	'title': '<table>{% for t in e.title %}<tr><td>{{t|escapejs}}</td></tr>{% endfor %}</table>',
},
{% endfor %}];
var network = visNetwork(nodes, edges);
</script>
-->
</div>
{% endblock%}

templates/drs_viz.html
{% extends "base.html" %}

{% block title %}
<title>STIX Defined Relationships</title>
{% endblock %}

{% block jquery %}
<script>
function drawvis(){
    var data = $("form").serialize();
    $.ajax({
            type: 'POST',
            url: '/data/drs/',
            data: data,
            success: function(result){
                var network = visNetwork(
                    result["nodes"],
                    result["edges"]
                );
                network.redraw();
            }
    });
};
$(document).ready(
    function(){
        drawvis();
        $("input#select_types").click(function(){
            if($(this).prop("checked")){
                $('ul#id_types :checkbox').prop('checked',true);
            }else{
                $('ul#id_types :checkbox').prop('checked',false);
            };
        });
        $("input#select_relation").click(function(){
            if($(this).prop("checked")){
                $('ul#id_relation :checkbox').prop('checked',true);
            }else{
                $('ul#id_relation :checkbox').prop('checked',false);
            };
        });
        $("input").change(function(){
            drawvis();
        });
    }
);
</script>
{% endblock %}

{% block container %}

<div class="col-md-12">
<div class="panel panel-primary">
<div class="panel-heading">STIX Defined Relationships</div>
<div class="panel-body">

<div class="col-md-7" style="margin: 0 auto;height:500px" id="network" ></div>

<div class="col-md-5" >
<form method=post>{% csrf_token %}
<div class="col-md-7" id="types_form">
<input type="checkbox" id="select_types" checked>types</input>
{{tsform.types}}
</div>
<div class="col-md-5" id="rel_form">
<input type="checkbox" id="select_relation" checked>relationship</input>
{{tsform.relation}}
</div>
</form>
</div>

</div><!--/panel-body-->
</div><!--/panel-->
</div>

<!--
<script type="text/javascript">
var nodes = [
{% for n in nodes %}{
	'id':'{{n.id}}',
	'label':'{{n.label}}',
	'group':'{{n.group}}',
	'title': '<table>{% for t in n.title %}<tr><td>{{t|escapejs}}</td></tr>{% endfor %}</table>',
},
{% endfor %}];

var edges = [
{% for e in edges %}{
	'from':'{{e.from}}',
	'to':'{{e.to}}',
	'label':'{{e.label}}',
	'title': '<table>{% for t in e.title %}<tr><td>{{t|escapejs}}</td></tr>{% endfor %}</table>',
},
{% endfor %}];
var network = visNetwork(nodes, edges);
</script>
-->
</div>
{% endblock%}

templates/indicator_list.html
{% extends "base_list.html" %}

{% block modal %}
<div class="modal" id="objtype_form" role="dialog">
<div class="modal-dialog">
<div class="modal-content">

<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h4 class="modal-title">Create {{objtype}}</h4>
</div>

<div class="modal-body">
<form method=post>{% csrf_token %}
<div class="col-md-12">
<div class="col-md-6">
<table>
{{form.as_table}}
</table>
</div>
<div class="col-md-6">
<table>
{{pformset.as_table}}
</table>
</div>
</div>
<input class="btn btn-primary btn-sm" type="submit" name="create" value="create">
</form>
</div><!--/.modal-body-->

</div><!--/.modal-content-->
</div><!--/.modal-dialog-->
</div><!--/.modal-->
{% endblock %}

{% block left_thead %}
<th class="col-md-2">ID</th>
<th class="col-md-4">Name</th>
<th class="col-md-6">Pattern</th>
{% endblock %}

{% block right_pane %}
{% endblock %}